# permissions for end users to view redisfailovers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: redisfailover-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: redis-operator
    app.kubernetes.io/part-of: redis-operator
    app.kubernetes.io/managed-by: kustomize
  name: redisfailover-viewer-role
rules:
- apiGroups:
  - databases.spotahome.com
  resources:
  - redisfailovers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - databases.spotahome.com
  resources:
  - redisfailovers/status
  verbs:
  - get
