---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - databases.spotahome.com
  resources:
  - redisfailovers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - databases.spotahome.com
  resources:
  - redisfailovers/finalizers
  verbs:
  - update
- apiGroups:
  - databases.spotahome.com
  resources:
  - redisfailovers/status
  verbs:
  - get
  - patch
  - update
